In [1]:
import numpy as np
import pandas as pd
import os

os.chdir('C://Users/manni/Desktop')

In [2]:
data = pd.read_csv("Merged Rainfall Data.csv", parse_dates=[0])
data

,date,adm2_id,ADM2_PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version,ADM2_EN,SENDIST_EN,ADM1_EN
0,2021-01-01,22980,NG029014,28.0,4.9286,3.2274,11.7857,9.9821,180.4643,220.9571,120.6772,109.0259,82.4674,final,Okitipupa,Ondo South,Ondo
1,2021-01-11,22980,NG029014,28.0,2.2143,3.7071,9.1429,10.3190,134.7500,149.4417,82.8548,94.2114,90.7856,final,Okitipupa,Ondo South,Ondo
2,2021-01-21,22980,NG029014,28.0,1.4643,6.0607,8.6071,12.9952,65.7500,82.5226,58.4437,80.9174,81.8719,final,Okitipupa,Ondo South,Ondo
3,2021-02-01,22980,NG029014,28.0,5.2143,9.3012,8.8929,19.0690,36.0357,62.3286,71.4226,64.9930,63.6480,final,Okitipupa,Ondo South,Ondo
4,2021-02-11,22980,NG029014,28.0,12.7143,15.7690,19.3929,31.1310,41.1429,63.6548,85.2918,71.4616,69.4359,final,Okitipupa,Ondo South,Ondo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123763,2025-05-11,23001,NG030013,33.0,33.6364,55.8818,127.5455,155.6455,364.3636,344.8535,63.4613,83.0361,105.4981,final,Ife North,Osun East,Osun
123764,2025-05-21,23001,NG030013,33.0,37.6061,62.2465,94.5152,173.8182,382.2121,395.3495,63.3581,56.8579,96.7590,final,Ife North,Osun East,Osun
123765,2025-06-01,23001,NG030013,33.0,86.4545,91.7434,157.6970,209.8717,451.2727,463.5848,94.5331,76.2704,97.4002,prelim,Ife North,Osun East,Osun
123766,2025-06-11,23001,NG030013,33.0,68.5152,83.6848,192.5758,237.6747,462.6970,514.2283,82.8948,81.7910,90.1701,prelim,Ife North,Osun East,Osun
123767,2025-06-21,23001,NG030013,33.0,111.9697,80.5343,266.9394,255.9626,504.5758,557.9889,136.7517,104.1272,90.5961,prelim,Ife North,Osun East,Osun

In [3]:
data.columns

Index(['date', 'adm2_id', 'ADM2_PCODE', 'n_pixels', 'rfh', 'rfh_avg', 'r1h',
       'r1h_avg', 'r3h', 'r3h_avg', 'rfq', 'r1q', 'r3q', 'version', 'ADM2_EN',
       'SENDIST_EN', 'ADM1_EN'],
      dtype='object')

In [4]:
df = data[data['ADM2_EN'] == "Kabba/Bunu"]
df = df[['date', 'rfh']]

df.set_index('date', inplace=True)

# --- Step 3: Resample to daily frequency and interpolate ---
# Create a new date range from the minimum to the maximum date in your data, daily frequency
full_date_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')

# Reindex the DataFrame to this full daily range, which will introduce NaNs for missing days
df_daily = df.reindex(full_date_range)

# Apply linear interpolation to fill the NaN values
df_interpolated = df_daily.interpolate(method='linear')
df = df_interpolated.reset_index()
df.columns = ['date', 'rfh']
df

           date       rfh
0    2021-01-01   1.20690
1    2021-01-02   1.18621
2    2021-01-03   1.16552
3    2021-01-04   1.14483
4    2021-01-05   1.12414
...         ...       ...
1628 2025-06-17  68.51956
1629 2025-06-18  67.59082
1630 2025-06-19  66.66208
1631 2025-06-20  65.73334
1632 2025-06-21  64.80460

[1633 rows x 2 columns]

In [5]:
import plotly.express as px
px.line(df, x = 'date', y = 'rfh', title='Rainfall Data', labels={'date': 'Date', 'rfh': 'Rainfall Height (mm)'})

In [6]:
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['day_of_year'] = df['date'].dt.dayofyear
df['week_of_year'] = df.day_of_year//7 + 1

df

           date       rfh  day  month  year  day_of_year  week_of_year
0    2021-01-01   1.20690    1      1  2021            1             1
1    2021-01-02   1.18621    2      1  2021            2             1
2    2021-01-03   1.16552    3      1  2021            3             1
3    2021-01-04   1.14483    4      1  2021            4             1
4    2021-01-05   1.12414    5      1  2021            5             1
...         ...       ...  ...    ...   ...          ...           ...
1628 2025-06-17  68.51956   17      6  2025          168            25
1629 2025-06-18  67.59082   18      6  2025          169            25
1630 2025-06-19  66.66208   19      6  2025          170            25
1631 2025-06-20  65.73334   20      6  2025          171            25
1632 2025-06-21  64.80460   21      6  2025          172            25

[1633 rows x 7 columns]

In [7]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score

X = df.drop(['date', 'day_of_year', 'rfh'], axis = 1)
y = df['rfh']

split_date = '2025-01-01'
# Try splitting 80% train, 20% test based on number of rows if a date split is problematic
split_idx = int(0.9*len(X))          #len(df[df['datetime'] <= split_date])

X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

# Training
model = RandomForestRegressor(n_estimators = 50, random_state = 42, n_jobs= -1, min_samples_leaf=8)
# model = GradientBoostingRegressor(random_state=42, n_estimators=100, learning_rate=0.1, max_depth=10)
model.fit(X_train, y_train)

#Accuracy
train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

train_accuracy, test_accuracy

(0.9501815804475838, 0.7356153927216159)

In [8]:
predictions = model.predict(X_test)

import plotly.express as px
import plotly.graph_objects as go # Needed for go.Scatter to add traces


fig = px.line(
    x=df['date'][:len(y_train)],
    y=y_train,
    labels={'x': 'Date', 'y': 'Value'}, # Add labels for clarity
    title='Time Series: Training, Test, and Predictions'
)

# 2. Add the actual test data as a new trace
fig.add_trace(
    go.Scatter(
        x=df['date'][len(y_train):],
        y=y_test,
        mode='lines',
        name='Actual Test Data', # Label for the legend
        line=dict(color='orange') # Optional: customize line color
    )
)

# 3. Add the predictions as another new trace
#    The x-axis for predictions should align with the test data.
fig.add_trace(
    go.Scatter(
        x=df['date'][len(y_train):],
        y=predictions,
        mode='lines',
        name='Model Predictions', # Label for the legend
        line=dict(color='green', dash='dot') # Optional: customize line color and style
    )
)

# Optional: Update layout for better readability
fig.update_layout(
    hovermode="x unified", # Shows all y-values at a given x-point on hover
    xaxis_title="Date",
    yaxis_title="Rainfall Height (mm)",
)

# Show the figure
fig.show()

In [9]:
from datetime import date

lga = "Kabba/Bunu"
df = data[data['ADM2_EN'] == lga]
df = df[['date', 'rfh']]

df.set_index('date', inplace=True)

full_date_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')

# Reindex the DataFrame to this full daily range, which will introduce NaNs for missing days
df_daily = df.reindex(full_date_range)

# Apply linear interpolation to fill the NaN values
df_interpolated = df_daily.interpolate(method='linear')
df = df_interpolated.reset_index()
df.columns = ['date', 'rfh']

df = df.reset_index().drop('index', axis = 1)

# Preprocessing
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['day_of_year'] = df['date'].dt.dayofyear
df['week_of_year'] = df.day_of_year//7 + 1

X = df.drop(['date', 'day_of_year', 'rfh'], axis = 1)
y = df['rfh']


# Training
model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
model.fit(X, y)


# Forecasting
forecast_start_date = df['date'].max()
forecast_end_date = forecast_start_date + pd.Timedelta(days = 365)
forecast_dates = pd.date_range(start=forecast_start_date, end=forecast_end_date, freq='D')
#print(f"Forecasting from {forecast_dates.min()} to {forecast_dates.max()} ({len(forecast_dates)} days).")
# Forecasting
forecast_start_date = df['date'].max()
forecast_dates = pd.date_range(start=forecast_start_date, end=date(2025,12,31), freq='D')

df1 = pd.DataFrame(forecast_dates)
df1.columns = ['date']
df1['day'] = df1['date'].dt.day
df1['month'] = df1['date'].dt.month
df1['year'] = df1['date'].dt.year
df1['day_of_year'] = df1['date'].dt.dayofyear
df1['week_of_year'] = df1.day_of_year//7 + 1
df1 = df1.drop(['date', 'day_of_year'], axis = 1)
prediction = model.predict(df1)

actual = df[df['date'] >= "2024-01-01"].copy()
actual['type'] = 'Actual'

pred = pd.DataFrame(forecast_dates)
pred.columns = ['date']
pred['rfh'] = prediction
pred['type'] = 'Forecasted'

full_df = pd.concat([actual, pred], axis = 0)
full_df['lga'] = lga

full_df = full_df[['lga','date', 'rfh', 'type']]
full_df

#forecast_df = pd.concat([forecast_df, full_df], axis = 0)

             lga       date       rfh        type
1095  Kabba/Bunu 2024-01-01  1.287400      Actual
1096  Kabba/Bunu 2024-01-02  1.258660      Actual
1097  Kabba/Bunu 2024-01-03  1.229920      Actual
1098  Kabba/Bunu 2024-01-04  1.201180      Actual
1099  Kabba/Bunu 2024-01-05  1.172440      Actual
...          ...        ...       ...         ...
189   Kabba/Bunu 2025-12-27  1.481176  Forecasted
190   Kabba/Bunu 2025-12-28  1.471130  Forecasted
191   Kabba/Bunu 2025-12-29  1.473491  Forecasted
192   Kabba/Bunu 2025-12-30  1.237887  Forecasted
193   Kabba/Bunu 2025-12-31  1.197584  Forecasted

[732 rows x 4 columns]

In [ ]:
bfig = px.line(full_df[full_df['type'] == 'Actual'],
    x = 'date',
    y = 'rfh',
              color = px.Constant('Actual Data'),
    labels = {'date': 'Date', 'rfh': 'Rainfall Height (mm)', 'color':'Legend'}, # Add labels for clarity
    title = 'Actual Data and Forecast'
)

# 2. Add the actual test data as a new trace
fig.add_trace(
    go.Scatter(
        x=full_df[full_df['type'] == 'Forecasted']['date'],
        y=full_df[full_df['type'] == 'Forecasted']['rfh'],
        mode='lines',
        name='Forecasted data', # Label for the legend
        line=dict(color='yellow') # Optional: customize line color
    )
)


# Show the figure
fig.show()

In [11]:
pd.read_csv("Merged Rainfall Data.csv", parse_dates=[0])

,date,adm2_id,ADM2_PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version,ADM2_EN,SENDIST_EN,ADM1_EN
0,2021-01-01,22980,NG029014,28.0,4.9286,3.2274,11.7857,9.9821,180.4643,220.9571,120.6772,109.0259,82.4674,final,Okitipupa,Ondo South,Ondo
1,2021-01-11,22980,NG029014,28.0,2.2143,3.7071,9.1429,10.3190,134.7500,149.4417,82.8548,94.2114,90.7856,final,Okitipupa,Ondo South,Ondo
2,2021-01-21,22980,NG029014,28.0,1.4643,6.0607,8.6071,12.9952,65.7500,82.5226,58.4437,80.9174,81.8719,final,Okitipupa,Ondo South,Ondo
3,2021-02-01,22980,NG029014,28.0,5.2143,9.3012,8.8929,19.0690,36.0357,62.3286,71.4226,64.9930,63.6480,final,Okitipupa,Ondo South,Ondo
4,2021-02-11,22980,NG029014,28.0,12.7143,15.7690,19.3929,31.1310,41.1429,63.6548,85.2918,71.4616,69.4359,final,Okitipupa,Ondo South,Ondo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123763,2025-05-11,23001,NG030013,33.0,33.6364,55.8818,127.5455,155.6455,364.3636,344.8535,63.4613,83.0361,105.4981,final,Ife North,Osun East,Osun
123764,2025-05-21,23001,NG030013,33.0,37.6061,62.2465,94.5152,173.8182,382.2121,395.3495,63.3581,56.8579,96.7590,final,Ife North,Osun East,Osun
123765,2025-06-01,23001,NG030013,33.0,86.4545,91.7434,157.6970,209.8717,451.2727,463.5848,94.5331,76.2704,97.4002,prelim,Ife North,Osun East,Osun
123766,2025-06-11,23001,NG030013,33.0,68.5152,83.6848,192.5758,237.6747,462.6970,514.2283,82.8948,81.7910,90.1701,prelim,Ife North,Osun East,Osun
123767,2025-06-21,23001,NG030013,33.0,111.9697,80.5343,266.9394,255.9626,504.5758,557.9889,136.7517,104.1272,90.5961,prelim,Ife North,Osun East,Osun

In [12]:
from datetime import date

data = pd.read_csv("Merged Rainfall Data.csv", parse_dates=[0])
#data = data.drop_duplicates(keep='first')

forecast_df = pd.DataFrame()

for lga in data['ADM2_EN'].unique():
    try:
        df = data[data['ADM2_EN'] == lga]
        df = df[['date', 'rfh']]

        if df.duplicated(subset=['date']).all():
            df['date'] = pd.to_datetime(df['date'])
            df.drop_duplicates(['date'], inplace=True)

        df.set_index('date', inplace=True)

        # --- Step 3: Resample to daily frequency and interpolate ---
        # Create a new date range from the minimum to the maximum date in your data, daily frequency
        full_date_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')
        full_date_range = full_date_range.drop_duplicates(keep='first')

        # Reindex the DataFrame to this full daily range, which will introduce NaNs for missing days
        df_daily = df.reindex(full_date_range)

        # Apply linear interpolation to fill the NaN values
        df_interpolated = df_daily.interpolate(method='linear')
        df = df_interpolated.reset_index()
        df.columns = ['date', 'rfh']

        df = data[data['ADM2_EN'] == lga]
        df = df[['date', 'rfh']]

        df.set_index('date', inplace=True)

        full_date_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')
        full_date_range.drop_duplicates()

        # Reindex the DataFrame to this full daily range, which will introduce NaNs for missing days
        df_daily = df.reindex(full_date_range)

        # Apply linear interpolation to fill the NaN values
        df_interpolated = df_daily.interpolate(method='linear')
        df = df_interpolated.reset_index()
        df.columns = ['date', 'rfh']

        df = df.reset_index().drop('index', axis = 1)

        # Preprocessing
        df['day'] = df['date'].dt.day
        df['month'] = df['date'].dt.month
        df['year'] = df['date'].dt.year
        df['day_of_year'] = df['date'].dt.dayofyear
        df['week_of_year'] = df.day_of_year//7 + 1

        X = df.drop(['date', 'day_of_year', 'rfh'], axis = 1)
        y = df['rfh']


        # Training
        model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
        model.fit(X, y)


        # Forecasting
        forecast_start_date = df['date'].max()
        forecast_end_date = forecast_start_date + pd.Timedelta(days = 365)
        forecast_dates = pd.date_range(start=forecast_start_date, end=forecast_end_date, freq='D')
        #print(f"Forecasting from {forecast_dates.min()} to {forecast_dates.max()} ({len(forecast_dates)} days).")
        # Forecasting
        forecast_start_date = df['date'].max()
        forecast_dates = pd.date_range(start=forecast_start_date, end=date(2025,12,31), freq='D')

        df1 = pd.DataFrame(forecast_dates)
        df1.columns = ['date']
        df1['day'] = df1['date'].dt.day
        df1['month'] = df1['date'].dt.month
        df1['year'] = df1['date'].dt.year
        df1['day_of_year'] = df1['date'].dt.dayofyear
        df1['week_of_year'] = df1.day_of_year//7 + 1
        df1 = df1.drop(['date', 'day_of_year'], axis = 1)
        prediction = model.predict(df1)

        actual = df[df['date'] >= "2024-01-01"].copy()
        actual['type'] = 'Actual'

        pred = pd.DataFrame(forecast_dates)
        pred.columns = ['date']
        pred['rfh'] = prediction
        pred['type'] = 'Forecasted'

        full_df = pd.concat([actual, pred], axis = 0)
        full_df['lga'] = lga

        full_df = full_df[['lga','date', 'rfh', 'type']]

        forecast_df = pd.concat([forecast_df, full_df], axis = 0)
        print("Done with ", lga)
    except Exception as e:
        print("Stopped at", lga)
        print(e, "has",df.duplicated().sum(), "duplicate entries")
        break

Done with  Okitipupa
Done with  Mai'adua
Done with  Taura
Done with  Toungo
Done with  Tofa
Done with  Toto
Done with  Tsanyawa
Done with  Tudun Wada
Done with  Tureta
Done with  Udenu
Done with  Udu
Done with  Udung Uko
Done with  Ughelli North
Done with  Ughelli South
Done with  Ugwunagbo
Done with  Uhunmwonde
Done with  Ukwuani
Done with  Tarmua
Done with  Umuahia North
Done with  Tarka
Done with  Tangaza
Done with  Shendam
Done with  Shinkafi
Done with  Shira
Done with  Shiroro
Done with  Shomgom
Stopped at Kware
cannot reindex on an axis with duplicate labels has 191 duplicate entries

In [36]:
lgas = pd.read_csv('Adm_Data_Names.csv')
lgas_dict = dict(zip(lgas['ADM2_PCODE'], lgas['ADM2_EN']))
for lga, code in lgas_dict.items():
    print(lga, code)

NG001001 Aba North
NG001002 Aba South
NG008001 Abadam
NG015001 Abaji
NG003001 Abak
NG011001 Abakaliki
NG028001 Abeokuta North
NG028002 Abeokuta South
NG009001 Abi
NG017001 Aboh-Mbaise
NG033001 Abua/Odual
NG015002 Abuja Municipal
NG023001 Adavi
NG007001 Ado
NG028003 Ado-Odo/Ota
NG013001 Ado Ekiti
NG031001 Afijio
NG011002 Afikpo North
NG011003 Afikpo South
NG027001 Agaie
NG007002 Agatu
NG025001 Agege
NG004001 Aguata
NG027002 Agwara
NG017002 Ahiazu-Mbaise
NG033002 Ahoada East
NG033003 Ahoada West
NG030001 Aiyedade
NG030002 Aiyedire
NG013002 Aiyekire (Gbonyin)
NG023002 Ajaokuta
NG025002 Ajeromi-Ifelodun
NG020001 Ajingi
NG009002 Akamkpa
NG031002 Akinyele
NG016001 Akko
NG012001 Akoko-Edo
NG029001 Akoko North East
NG029002 Akoko North West
NG029003 Akoko South East
NG029004 Akoko South West
NG009003 Akpabuyo
NG033004 Akuku Toru
NG029005 Akure North
NG029006 Akure South
NG026001 Akwanga
NG020002 Albasu
NG022001 Aleiro
NG025003 Alimosho
NG005001 Alkaleri
NG025004 Amuwo-Odofin
NG004002 Anambra East
NG004003 Anambra West
NG004004 Anaocha
NG033005 Andoni
NG014001 Aninri
NG010001 Aniocha North
NG010002 Aniocha South
NG037001 Anka
NG023003 Ankpa
NG007003 Apa
NG025005 Apapa
NG035001 Ardo-Kola
NG022002 Arewa-Dandi
NG022003 Argungu
NG001003 Arochukwu
NG024001 Asa
NG033006 Asari-Toru
NG008002 Askira/Uba
NG030003 Atakumosa East
NG030004 Atakumosa West
NG031003 Atiba
NG031004 Atigbo
NG022004 Augie
NG018001 Auyo
NG026002 Awe
NG014002 Awgu
NG004005 Awka North
NG004006 Awka South
NG004007 Ayamelum
NG018002 Babura
NG025006 Badagry
NG036001 Bade
NG022005 Bagudo
NG020003 Bagwai
NG009005 Bakassi
NG021001 Bakori
NG037002 Bakura
NG016002 Balanga
NG035002 Bali
NG008003 Bama
NG032001 Barikin Ladi
NG024002 Baruten
NG023004 Bassa
NG032002 Bassa
NG021002 Batagarawa
NG021003 Batsari
NG005002 Bauchi
NG021004 Baure
NG008004 Bayo
NG020004 Bebeji
NG009006 Bekwara
NG001004 Bende
NG009007 Biase
NG020005 Bichi
NG027003 Bida
NG016003 Billiri
NG021005 Bindawa
NG034001 Binji
NG018003 Biriniwa
NG018004 Birni Kudu
NG019001 Birnin-Gwari
NG022006 Birnin Kebbi
NG037003 Birnin Magaji
NG008005 Biu
NG034002 Bodinga
NG005003 Bogoro
NG009008 Boki
NG032003 Bokkos
NG030005 Boluwaduro
NG010003 Bomadi
NG033007 Bonny
NG027004 Borgu
NG030006 Boripe
NG027005 Bosso
NG006001 Brass
NG018005 Buji
NG037004 Bukkuyum
NG037005 Bungudu
NG020006 Bunkure
NG022007 Bunza
NG036002 Bursari
NG007004 Buruku
NG010004 Burutu
NG015003 Bwari
NG009010 Calabar-Municipal
NG009009 Calabar South
NG027006 Chanchaga
NG021006 Charanchi
NG008006 Chibok
NG019002 Chikun
NG020007 Dala
NG036003 Damaturu
NG005004 Damban
NG020008 Dambatta
NG008007 Damboa
NG021007 Dan Musa
NG022008 Dandi
NG021008 Dandume
NG034003 Dange-Shuni
NG021009 Danja
NG005005 Darazo
NG005006 Dass
NG021010 Daura
NG020009 Dawakin Kudu
NG020010 Dawakin Tofa
NG033008 Degema
NG023005 Dekina
NG002001 Demsa
NG008008 Dikwa
NG020011 Doguwa
NG026003 Doma
NG035003 Donga
NG016004 Dukku
NG004008 Dunukofia
NG018006 Dutse
NG021011 Dutsi
NG021012 Dutsin-Ma
NG003002 Eastern Obolo
NG011004 Ebonyi
NG027007 Edati
NG030007 Ede North
NG030008 Ede South
NG024003 Edu
NG013003 Efon
NG028004 Egbado North
NG028005 Egbado South
NG031005 Egbeda
NG030009 Egbedore
NG012002 Egor
NG017003 Ehime-Mbano
NG030010 Ejigbo
NG006002 Ekeremor
NG003003 Eket
NG024004 Ekiti
NG013004 Ekiti East
NG013005 Ekiti South West
NG013006 Ekiti West
NG004009 Ekwusigo
NG033009 Eleme
NG033010 Emohua
NG013007 Emure
NG014003 Enugu East
NG014004 Enugu North
NG014005 Enugu South
NG025007 Epe
NG012003 Esan Central
NG012004 Esan North East
NG012005 Esan South East
NG012006 Esan West
NG029007 Ese-Odo
NG003004 Esit - Eket
NG003005 Essien Udim
NG033011 Etche
NG010005 Ethiope East
NG010006 Ethiope West
NG025008 Eti-Osa
NG003006 Etim Ekpo
NG003007 Etinan
NG012007 Etsako Central
NG012008 Etsako East
NG012009 Etsako West
NG009011 Etung
NG028006 Ewekoro
NG014006 Ezeagu
NG017004 Ezinihitte
NG011005 Ezza North
NG011006 Ezza South
NG020012 Fagge
NG022009 Fakai
NG021013 Faskari
NG036004 Fika
NG002002 Fufore
NG016005 Funakaye
NG036005 Fune
NG021014 Funtua
NG020013 Gabasawa
NG034004 Gada
NG018007 Gagarawa
NG005007 Gamawa
NG005008 Ganjuwa
NG002003 Ganye
NG018008 Garki
NG020014 Garko
NG020015 Garum Mallam
NG035004 Gashaka
NG035005 Gassol
NG020016 Gaya
NG027008 Gbako
NG007005 Gboko
NG036006 Geidam
NG020017 Gezawa
NG005009 Giade
NG002005 Girei
NG019003 Giwa
NG033012 Gokana
NG016006 Gombe
NG002004 Gombi
NG034006 Goronyo
NG008009 Gubio
NG034007 Gudu
NG036007 Gujba
NG036008 Gulani
NG007006 Guma
NG018009 Gumel
NG037006 Gummi
NG027009 Gurara
NG018010 Guri
NG037007 Gusau
NG002006 Guyuk
NG008010 Guzamala
NG034005 Gwadabawa
NG015004 Gwagwalada
NG020018 Gwale
NG022010 Gwandu
NG018011 Gwaram
NG020019 Gwarzo
NG007007 Gwer East
NG007008 Gwer West
NG018012 Gwiwa
NG008011 Gwoza
NG018013 Hadejia
NG008012 Hawul
NG002007 Hong
NG031006 Ibadan North
NG031007 Ibadan North East
NG031008 Ibadan North West
NG031009 Ibadan South East
NG031010 Ibadan South West
NG023006 Ibaji
NG031011 Ibarapa Central
NG031012 Ibarapa East
NG031013 Ibarapa North
NG025009 Ibeju/Lekki
NG003008 Ibeno
NG003009 Ibesikpo Asutan
NG035006 Ibi
NG003010 Ibiono Ibom
NG023007 Idah
NG029008 Idanre
NG017005 Ideato North
NG017006 Ideato South
NG004010 Idemili North
NG004011 Idemili South
NG031014 Ido
NG013008 Ido-Osi
NG025010 Ifako-Ijaye
NG030011 Ife Central
NG030012 Ife East
NG030013 Ife North
NG030014 Ife South
NG030015 Ifedayo
NG029009 Ifedore
NG024005 Ifelodun
NG030016 Ifelodun
NG028007 Ifo
NG019004 Igabi
NG023008 Igalamela-Odolu
NG014007 Igbo-Etiti
NG014008 Igbo-Eze North
NG014009 Igbo-Eze South
NG012010 Igueben
NG004012 Ihiala
NG017007 Ihitte/Uboma
NG028008 Ijebu East
NG028009 Ijebu North
NG028010 Ijebu North East
NG028011 Ijebu Ode
NG013009 Ijero
NG023009 Ijumu
NG003011 Ika
NG010007 Ika North East
NG010008 Ika South
NG019005 Ikara
NG017008 Ikeduru
NG025011 Ikeja
NG028012 Ikenne
NG013010 Ikere
NG013011 Ikole
NG009012 Ikom
NG003012 Ikono
NG025012 Ikorodu
NG003013 Ikot Abasi
NG003014 Ikot Ekpene
NG012011 Ikpoba-Okha
NG033013 Ikwerre
NG011007 Ikwo
NG001005 Ikwuano
NG030017 Ila
NG029010 Ilaje
NG029011 Ile-Oluji-Okeigbo
NG013012 Ilejemeji
NG030018 Ilesha East
NG030019 Ilesha West
NG034008 Illela
NG024006 Ilorin East
NG024007 Ilorin South
NG024008 Ilorin West
NG028013 Imeko-Afon
NG021015 Ingawa
NG003015 Ini
NG028014 Ipokia
NG029012 Irele
NG031015 Irepo
NG024009 Irepodun
NG030020 Irepodun
NG013013 Irepodun/Ifelodun
NG030021 Irewole
NG034009 Isa
NG013014 Ise/Orun
NG031016 Iseyin
NG011008 Ishielu
NG014010 Isi-Uzo
NG001006 Isiala-Ngwa North
NG001007 Isiala-Ngwa South
NG017009 Isiala Mbano
NG024010 Isin
NG001008 Isiukwuato
NG030022 Isokan
NG010009 Isoko North
NG010010 Isoko South
NG017010 Isu
NG005010 Itas/Gadau
NG031017 Itesiwaju
NG003016 Itu
NG011009 Ivo
NG031018 Iwajowa
NG030023 Iwo
NG011010 Izzi
NG019006 Jaba
NG002008 Jada
NG018014 Jahun
NG036009 Jakusko
NG035007 Jalingo
NG005011 Jama'are
NG022011 Jega
NG019007 Jema'a
NG008013 Jere
NG021016 Jibia
NG032004 Jos East
NG032005 Jos North
NG032006 Jos South
NG023010 Kabba/Bunu
NG020020 Kabo
NG019008 Kachia
NG019009 Kaduna North
NG019010 Kaduna South
NG018015 Kafin Hausa
NG021017 Kafur
NG008014 Kaga
NG019011 Kagarko
NG024011 Kaiama
NG021018 Kaita
NG031019 Kajola
NG019012 Kajuru
NG008015 Kala/Balge
NG022012 Kalgo
NG016007 Kaltungo
NG032007 Kanam
NG021019 Kankara
NG032008 Kanke
NG021020 Kankia
NG020021 Kano Municipal
NG036010 Karasuwa
NG020022 Karaye
NG035008 Karim-Lamido
NG026004 Karu
NG005012 Katagum
NG027010 Katcha
NG021021 Katsina
NG007009 Katsina-Ala
NG018016 Kaugama
NG019013 Kaura
NG037008 Kaura Namoda
NG019014 Kauru
NG018017 Kazaure
NG026005 Keana
NG034010 Kebbe
NG026006 Keffi
NG033014 Khana
NG020023 Kibiya
NG005013 Kirfi
NG018018 Kiri Kasamma
NG020024 Kiru
NG018019 Kiyawa
NG023011 Kogi
NG022013 Koko/Besse
NG026007 Kokona
NG006003 Kolokuma/Opokuma
NG008016 Konduga
NG007010 Konshisha
NG027011 Kontagora
NG025013 Kosofe
NG019015 Kubau
NG019016 Kudan
NG015005 Kuje
NG008017 Kukawa
NG020025 Kumbotso
NG020026 Kunchi
NG020027 Kura
NG021022 Kurfi
NG035009 Kurmi
NG021023 Kusada
NG015006 Kwali
NG016008 Kwami
NG007011 Kwande
NG034011 Kware
NG008018 Kwaya Kusar
NG026008 Lafia
NG031020 Lagelu
NG025014 Lagos Island
NG025015 Lagos Mainland
NG002009 Lamurde
NG032009 Langtang North
NG032010 Langtang South
NG027012 Lapai
NG035010 Lau
NG027013 Lavun
NG019017 Lere
NG007012 Logo
NG023012 Lokoja
NG036011 Machina
NG002010 Madagali
NG020028 Madobi
NG008019 Mafa
NG027014 Magama
NG008020 Magumeri
NG021024 Mai'adua
NG008021 Maiduguri
NG018020 Maigatari
NG002011 Maiha
NG022014 Maiyama
NG020029 Makoda
NG007013 Makurdi
NG018021 Malam Madori
NG021025 Malumfashi
NG032011 Mangu
NG021026 Mani
NG037009 Maradun
NG027015 Mariga
NG019018 Markafi
NG008022 Marte
NG037010 Maru
NG027016 Mashegu
NG021027 Mashi
NG021028 Matazu
NG002012 Mayo-Belwa
NG017011 Mbaitoli
NG003017 Mbo
NG002013 Michika
NG018022 Miga
NG032012 Mikang
NG020030 Minjibir
NG005014 Misau
NG003018 Mkpat Enin
NG013015 Moba
NG008023 Mobbar
NG027017 Mokwa
NG008024 Monguno
NG023013 Mopa-Muro
NG024012 Moro
NG002014 Mubi North
NG002015 Mubi South
NG021029 Musawa
NG025016 Mushin
NG027018 Muya
NG016009 Nafada
NG036012 Nangere
NG020031 Nasarawa
NG026009 Nasarawa
NG026010 Nasarawa-Eggon
NG010011 Ndokwa East
NG010012 Ndokwa West
NG006004 Nembe
NG008025 Ngala
NG008026 Nganzai
NG022015 Ngaski
NG017012 Ngor-Okpala
NG036013 Nguru
NG005015 Ningi
NG017013 Njaba
NG004013 Njikoka
NG014011 Nkanu East
NG014012 Nkanu West
NG017014 Nkwerre
NG004014 Nnewi North
NG004015 Nnewi South
NG003019 Nsit Atai
NG003020 Nsit Ibom
NG003021 Nsit Ubium
NG014013 Nsukka
NG002016 Numan
NG017015 Nwangele
NG028015 Obafemi-Owode
NG009013 Obanliku
NG007014 Obi
NG026011 Obi
NG001009 Obi Ngwa
NG033015 Obia/Akpor
NG030024 Obokun
NG003022 Obot Akara
NG017016 Obowo
NG009014 Obubra
NG009015 Obudu
NG028016 Odeda
NG029013 Odigbo
NG030025 Odo-Otin
NG028017 Odogbolu
NG009016 Odukpani
NG024013 Offa
NG023014 Ofu
NG033016 Ogba/Egbema/Ndoni
NG007015 Ogbadibo
NG004016 Ogbaru
NG006005 Ogbia
NG031021 Ogbomosho North
NG031022 Ogbomosho South
NG031023 Ogo Oluwa
NG009017 Ogoja
NG023015 Ogori/Magongo
NG033017 Ogu/Bolo
NG028018 Ogun waterside
NG017017 Oguta
NG001010 Ohafia
NG017018 Ohaji/Egbema
NG011011 Ohaozara
NG011012 Ohaukwu
NG007016 Ohimini
NG014014 Oji-River
NG025017 Ojo
NG007017 Oju
NG024014 Oke-Ero
NG023016 Okehi
NG023017 Okene
NG017019 Okigwe
NG029014 Okitipupa
NG003023 Okobo
NG010013 Okpe
NG007018 Okpokwu
NG033018 Okrika
NG030026 Ola-oluwa
NG023018 Olamabolo
NG030027 Olorunda
NG031024 Olorunsogo
NG031025 Oluyole
NG023019 Omala
NG033019 Omumma
NG031026 Ona-Ara
NG029015 Ondo East
NG029016 Ondo West
NG011013 Onicha
NG004017 Onitsha North
NG004018 Onitsha South
NG003024 Onna
NG033020 Opobo/Nkoro
NG012012 Oredo
NG031027 Orelope
NG012013 Orhionmwon
NG031028 Ori Ire
NG030028 Oriade
NG017020 Orlu
NG030029 Orolu
NG003025 Oron
NG017021 Orsu
NG017022 Oru East
NG017023 Oru West
NG003026 Oruk Anam
NG004019 Orumba North
NG004020 Orumba South
NG029017 Ose
NG010014 Oshimili North
NG010015 Oshimili South
NG025018 Oshodi-Isolo
NG001011 Osisioma Ngwa
NG030030 Osogbo
NG007019 Oturkpo
NG012014 Ovia North East
NG012015 Ovia South West
NG012016 Owan East
NG012017 Owan West
NG017026 Owerri-Municipal
NG017024 Owerri North
NG017025 Owerri West
NG029018 Owo
NG013016 Oye
NG004021 Oyi
NG033021 Oyigbo
NG031029 Oyo East
NG031030 Oyo West
NG024015 Oyun
NG027019 Paikoro
NG032013 Pankshin
NG010016 Patani
NG024016 Pategi
NG033022 Port-Harcourt
NG036014 Potiskum
NG032014 Qua'an Pan
NG034012 Rabah
NG027020 Rafi
NG020032 Rano
NG028019 Remo North
NG027021 Rijau
NG021030 Rimi
NG020033 Rimin Gado
NG018023 Ringim
NG032015 Riyom
NG020034 Rogo
NG018024 Roni
NG019019 Sabon-Gari
NG034013 Sabon Birni
NG021031 Sabuwa
NG021032 Safana
NG006006 Sagbama
NG022016 Sakaba
NG031031 Saki East
NG031032 Saki West
NG021033 Sandamu
NG019020 Sanga
NG010017 Sapele
NG035011 Sardauna
NG028020 Shagamu
NG034014 Shagari
NG022017 Shanga
NG008027 Shani
NG020035 Shanono
NG002017 Shelleng
NG032016 Shendam
NG037011 Shinkafi
NG005016 Shira
NG027022 Shiroro
NG016010 Shomgom
NG025019 Shomolu
NG034015 Silame
NG019021 Soba
NG034016 Sokoto North
NG034017 Sokoto South
NG002018 Song
NG006007 Southern Ijaw
NG018025 Sule-Tankarkar
NG027023 Suleja
NG020036 Sumaila
NG022018 Suru
NG025020 Surulere
NG031033 Surulere
NG027024 Tafa
NG005017 Tafawa-Balewa
NG033023 Tai
NG020037 Takai
NG035012 Takum
NG037012 Talata Mafara
NG034018 Tambuwal
NG034019 Tangaza
NG020038 Tarauni
NG007020 Tarka
NG036015 Tarmua
NG018026 Taura
NG020039 Tofa
NG005018 Toro
NG026012 Toto
NG002019 Toungo
NG037013 Tsafe
NG020040 Tsanyawa
NG020041 Tudun Wada
NG034020 Tureta
NG014015 Udenu
NG014016 Udi
NG010018 Udu
NG003027 Udung Uko
NG010019 Ughelli North
NG010020 Ughelli South
NG001012 Ugwunagbo
NG012018 Uhunmwonde
NG003028 Ukanafun
NG007021 Ukum
NG001013 Ukwa East
NG001014 Ukwa West
NG010021 Ukwuani
NG001017 Umu-Nneochi
NG001015 Umuahia North
NG001016 Umuahia South
NG020042 Ungogo
NG017027 Unuimo
NG003029 Uruan
NG003030 Urue-Offong/Oruko
NG007022 Ushongo
NG035013 Ussa
NG010022 Uvwie
NG003031 Uyo
NG014017 Uzo-Uwani
NG007023 Vandeikya
NG034021 Wamako
NG026013 Wamba
NG020043 Warawa
NG005019 Warji
NG010023 Warri North
NG010024 Warri South
NG010025 Warri South West
NG022019 Wasagu/Danko
NG032017 Wase
NG020044 Wudil
NG035014 Wukari
NG034022 Wurno
NG027025 Wushishi
NG034023 Yabo
NG023020 Yagba East
NG023021 Yagba West
NG009018 Yakurr
NG009019 Yala
NG016011 Yamaltu/Deba
NG018027 Yankwashi
NG022020 Yauri
NG006008 Yenegoa
NG002020 Yola North
NG002021 Yola South
NG035015 Yorro
NG036016 Yunusari
NG036017 Yusufari
NG005020 Zaki
NG021034 Zango
NG019022 Zango-Kataf
NG019023 Zaria
NG035016 Zing
NG037014 Zurmi
NG022021 Zuru

In [41]:
import pandas as pd
from datetime import date # Keep this import, though 'date(2025,12,31)' is likely the main use
from sklearn.ensemble import RandomForestRegressor

lgas = pd.read_csv('Adm_Data_Names.csv')
lgas_dict = dict(zip(lgas['ADM2_PCODE'], lgas['ADM2_EN']))
len(lags_dict)

# --- Configuration ---
DATA_FILE = "Merged Rainfall Data.csv"
TARGET_COLUMN = 'rfh'
LGA_COLUMN = 'ADM2_PCODE' # Assuming 'ADM2_EN' is the LGA identifier
VERSION_COLUMN = 'version' # Assuming you also have a 'version' column for filtering 'final'

# Initialize an empty DataFrame to store all forecasts
all_lga_forecast_df = pd.DataFrame()

# Load the full dataset once
data = pd.read_csv(DATA_FILE, parse_dates=[0]) # parse_dates=[0] means parse the first column as date

# Ensure the date column is datetime type for all operations
data['date'] = pd.to_datetime(data['date'])

# Iterate through each unique LGA
for lga in data[LGA_COLUMN].unique():                  #lga here is the lga code and the code is the lga name
    try:
        #print(f"\nProcessing LGA: {lga}")

        # --- Step 1: Filter Data for current LGA and 'final' version ---
        # Get data for the specific LGA
        df_lga = data[data[LGA_COLUMN] == lga].copy() # Use .copy() to avoid SettingWithCopyWarning

        # Filter for 'final' version data (if applicable and available in your CSV)
        # If your CSV doesn't have a 'version' column, you can remove this line
        if VERSION_COLUMN in df_lga.columns:
            df_lga = df_lga[df_lga[VERSION_COLUMN] == 'final'].copy()


        # --- Step 2: Prepare Dekadal Data for Daily Interpolation ---
        # Select only the date and target rainfall column
        df_lga_dekadal = df_lga[['date', TARGET_COLUMN]].copy()

        # Check for duplicates on the 'date' column within this LGA's dekadal data
        # If any duplicates exist for the same date, drop them (e.g., keep the first)
        if df_lga_dekadal.duplicated(subset=['date']).any():
            print(f"  Warning: Duplicate dates found for {lga}. Dropping duplicates, keeping first.")
            df_lga_dekadal.drop_duplicates(subset=['date'], inplace=True)

        # Set 'date' as the index
        df_lga_dekadal.set_index('date', inplace=True)

        # Sort the index to ensure chronological order (crucial for time series)
        df_lga_dekadal.sort_index(inplace=True)

        # Check if index is unique AFTER setting it and sorting
        if not df_lga_dekadal.index.is_unique:
             print(f"  CRITICAL ERROR: Index for {lga} is NOT UNIQUE after deduplication and setting. This should not happen.")
             # You might want to break here or log more detailed info if this occurs
             continue # Skip to next LGA if index is not unique

        # --- Step 3: Resample to daily frequency and interpolate ---
        # Create a new date range from the minimum to the maximum date in this LGA's data, daily frequency
        full_date_range = pd.date_range(start=df_lga_dekadal.index.min(),
                                        end=df_lga_dekadal.index.max(),
                                        freq='D')

        # Reindex the DataFrame to this full daily range, which will introduce NaNs for missing days
        # This is the line that caused the error, but should now work if df_lga_dekadal.index is unique
        df_daily_interpolated = df_lga_dekadal.reindex(full_date_range)

        # Apply linear interpolation to fill the NaN values
        df_daily_interpolated = df_daily_interpolated.interpolate(method='linear')

        # Reset index to make 'date' a column again for feature engineering
        df_processed = df_daily_interpolated.reset_index()
        df_processed.columns = ['date', TARGET_COLUMN] # Ensure column names are correct


        # --- Step 4: Feature Engineering for RandomForestRegressor ---
        df_processed['day'] = df_processed['date'].dt.day
        df_processed['month'] = df_processed['date'].dt.month
        df_processed['year'] = df_processed['date'].dt.year # Consider if 'year' is a good feature for generalization
        df_processed['day_of_year'] = df_processed['date'].dt.dayofyear
        df_processed['week_of_year'] = df_processed['day_of_year'] // 7 + 1


        # Define features (X) and target (y)
        # Assuming you want to predict 'rfh' based on date-derived features
        features_for_rf = ['day', 'month', 'year', 'week_of_year'] # day_of_year is often redundant with week_of_year, month, day
        X = df_processed[features_for_rf]
        y = df_processed[TARGET_COLUMN]

        # --- Step 5: Training the RandomForestRegressor ---
        model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
        model.fit(X, y)


        # --- Step 6: Forecasting ---
        # Define forecast period (e.g., from last historical date to end of next year)
        # Let's adjust forecast_start_date to be the day *after* the last historical day
        forecast_start_date = df_processed['date'].max() + pd.Timedelta(days=1)
        forecast_end_date = date(2025, 12, 31) # Forecasting up to end of 2025 as in your code

        forecast_dates = pd.date_range(start=forecast_start_date, end=forecast_end_date, freq='D')

        # Create DataFrame for forecast features
        df_forecast_features = pd.DataFrame(forecast_dates, columns=['date'])
        df_forecast_features['day'] = df_forecast_features['date'].dt.day
        df_forecast_features['month'] = df_forecast_features['date'].dt.month
        df_forecast_features['year'] = df_forecast_features['date'].dt.year
        df_forecast_features['day_of_year'] = df_forecast_features['date'].dt.dayofyear
        df_forecast_features['week_of_year'] = df_forecast_features['day_of_year'] // 7 + 1

        # Select only the features the model was trained on
        X_forecast = df_forecast_features[features_for_rf]

        # Make predictions
        predictions = model.predict(X_forecast)

        # --- Step 7: Combine Actual and Forecasted Data ---
        # Get actual data for plotting/comparison (from 2024-01-01 as in your code)
        actual_data_for_plot = df_processed[df_processed['date'] >= pd.to_datetime("2024-01-01")].copy()
        actual_data_for_plot['type'] = 'Actual'

        # Create DataFrame for forecasted results
        forecasted_data_df = pd.DataFrame({
            'date': forecast_dates,
            TARGET_COLUMN: predictions,
            'type': 'Forecasted'
        })

        # Concatenate actuals and forecasts for this LGA
        lga_full_df = pd.concat([actual_data_for_plot, forecasted_data_df], axis=0)
        lga_full_df[LGA_COLUMN] = lga # Add LGA identifier
        lga_full_df['ADM2_EN'] = lgas_dict[lga] # Add LGA identifier

        lga_full_df = lga_full_df[[LGA_COLUMN, 'ADM2_EN', 'date', TARGET_COLUMN, 'type']]


        # --- Step 8: Append to overall forecast DataFrame ---
        all_lga_forecast_df = pd.concat([all_lga_forecast_df, lga_full_df], axis=0)

        #print(f"  Successfully processed {lga}.")

    except Exception as e:
        print(f"  Stopped at LGA: {lga}")
        # Make sure df_lga_dekadal is defined before checking its index if error occurs early
        if 'df_lga_dekadal' in locals() and not df_lga_dekadal.index.is_unique:
             print(f"  Error likely due to non-unique index in {lga}. Index duplicates: {df_lga_dekadal.index[df_lga_dekadal.index.duplicated()].tolist()}")
        print(f"  Error message: {e}")
        # If you want to break the loop on first error, keep `break` here:
        # break
        # If you want to continue to the next LGA despite errors, remove `break`

  Warning: Duplicate dates found for NG034011. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG034003. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG020025. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG035015. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG002002. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG002005. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG009016. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG022017. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG033011. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG004016. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG031023. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG025003. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG004021. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG025004. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG017015. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG020042. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG002001. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG029011. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG030004. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG018001. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG030014. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG030009. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG008017. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG008013. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG026004. Dropping duplicates, keeping first.
  Warning: Duplicate dates found for NG002017. Dropping duplicates, keeping first.

In [42]:
all_lga_forecast_df

     ADM2_PCODE    ADM2_EN       date       rfh        type
1095   NG029014  Okitipupa 2024-01-01  1.821400      Actual
1096   NG029014  Okitipupa 2024-01-02  1.739260      Actual
1097   NG029014  Okitipupa 2024-01-03  1.657120      Actual
1098   NG029014  Okitipupa 2024-01-04  1.574980      Actual
1099   NG029014  Okitipupa 2024-01-05  1.492840      Actual
...         ...        ...        ...       ...         ...
219    NG030013  Ife North 2025-12-27  1.004018  Forecasted
220    NG030013  Ife North 2025-12-28  1.000644  Forecasted
221    NG030013  Ife North 2025-12-29  1.000644  Forecasted
222    NG030013  Ife North 2025-12-30  1.000644  Forecasted
223    NG030013  Ife North 2025-12-31  1.000644  Forecasted

[538016 rows x 5 columns]

In [43]:
all_lga_forecast_df.to_csv('Rainfall Forecast.csv', index=False)

In [99]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 4828-5060

 Directory of C:\Users\manni\Desktop

07/10/2025  02:49 PM    <DIR>          .
07/10/2025  08:03 AM    <DIR>          ..
06/27/2025  05:57 PM    <DIR>          .ipynb_checkpoints
07/08/2025  02:05 PM            84,369 Adm_Data_Names.csv
06/26/2025  10:31 AM        26,111,715 Append1.xlsx
07/01/2025  08:16 AM        12,802,968 Approved Sid-Trac Profile complete.pdf
06/10/2025  06:51 AM    <DIR>          Arewa DS Project
06/22/2025  03:56 AM    <DIR>          Aud
05/14/2025  06:05 PM        94,759,766 Brand_Assets[1].zip
06/19/2025  11:14 AM             1,402 CapCut.lnk
05/14/2025  07:57 PM             2,403 Carnac.lnk
06/26/2025  10:29 AM        49,273,954 Different States.xlsx
05/13/2025  10:55 AM             1,091 DroidCamApp.lnk
05/31/2025  04:16 AM    <DIR>          EPL Project
06/09/2025  07:01 PM             2,369 GitHub Desktop.lnk
07/06/2025  01:20 PM             2,278 Google Chrome.lnk
07/09/2025  02:48 PM             1,541 Grammarly.lnk
06/30/2025  05:53 PM    <DIR>          Learning Materials
06/24/2025  07:34 PM        12,017,890 Location Data.xlsx
07/04/2025  07:25 AM             5,987 Marcel_DemoGame.ipynb
07/08/2025  02:06 PM        16,836,340 Merged Rainfall Data.csv
05/13/2025  11:54 AM             1,312 Microsoft 365 Copilot.lnk
07/06/2025  08:26 PM    <DIR>          Mock Exams
06/24/2025  09:46 AM    <DIR>          NEMA Project Available Data
06/21/2025  01:53 PM        14,819,658 NEMA Project Available Data-20250621T063330Z-1-001.zip
06/27/2025  06:04 PM             1,378 nema_offices_nigeria.csv
07/08/2025  01:42 PM        13,215,205 nga-rainfall-adm2-5ytd.csv
07/08/2025  01:42 PM       130,759,377 nga-rainfall-adm2-full.csv
10/31/2024  02:35 PM     1,275,195,392 QGIS-OSGeo4W-3.38.3-1.msi
07/10/2025  02:49 PM        21,991,601 Rainfall Forecast.csv
06/26/2025  10:35 AM            10,309 River Stations and Coordinates - Copy.xlsx
06/26/2025  03:01 PM             1,126 River Stations and Coordinates.csv
06/26/2025  02:41 PM            10,232 River Stations and Coordinates.xlsx
06/24/2025  08:52 PM             9,908 Settlements_within_10km_radius.csv
06/27/2025  06:05 PM         1,402,931 Settlements_within_20km_radius_of_stations.csv
06/26/2025  03:05 PM         5,078,632 Settlements_within_50km_radius_of_stations.csv
06/27/2025  05:56 PM         2,306,044 Settlements_with_NEMA_Proximity.csv
06/27/2025  06:05 PM         2,072,608 Settlements_with_NEMA_Proximity_with_ID.csv
05/19/2025  10:59 AM             1,392 Spotify.lnk
06/25/2025  11:35 AM           254,267 State Wards with Cost.csv.xlsx
06/24/2025  08:44 PM         7,063,804 States & Coordinates Fact Table csv.csv
06/24/2025  08:35 PM        39,015,918 States & Coordinates Fact Table.csv
06/24/2025  08:35 PM        23,739,363 States & Coordinates Fact Table.xlsx
06/27/2025  06:07 PM            68,697 Untitled.ipynb
              35 File(s)  1,748,923,227 bytes
               9 Dir(s)   8,987,693,056 bytes free